import Head from 'next/head';
import Image from 'next/image';
import { Footer } from '../components/Footer';
import { Links } from '../components/Links';
import { Headlines } from '../components/Headlines';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Headlines title='Index Page' pageName='index' />
        <Links />
      </main>
      <Footer />
    </div>
  );
}
